export const fonts = {
	largeTitle: {
		fontFamily: 'OpenSans',
		fontStyle: 'normal',
		fontWeight: 'normal',
		fontSize: 34,
		lineHeight: 41,
		letterSpacing: 0.374,
	},
	title1: {
		fontFamily: 'OpenSans',
		fontStyle: 'normal',
		fontWeight: 'normal',
		fontSize: 28,
		lineHeight: 34,
		letterSpacing: 0.364,
	},
	title2: {
		fontFamily: 'OpenSans',
		fontStyle: 'normal',
		fontWeight: 'normal',
		fontSize: 22,
		lineHeight: 28,
		letterSpacing: 0.35,
	},
	title3: {
		fontFamily: 'OpenSans',
		fontStyle: 'normal',
		fontWeight: 'normal',
		fontSize: 20,
		lineHeight: 24,
		letterSpacing: 0.38,
	},
	headline: {
		fontFamily: 'OpenSans',
		fontStyle: 'normal',
		fontWeight: 600,
		fontSize: 18,
		lineHeight: 22,
		letterSpacing: -0.408,
	},
	body: {
		fontFamily: 'OpenSans',
		fontStyle: 'normal',
		fontWeight: 'normal',
		fontSize: 17,
		lineHeight: 22,
		letterSpacing: -0.408,
	},
	callout: {
		fontFamily: 'OpenSans',
		fontStyle: 'normal',
		fontWeight: 'normal',
		fontSize: 16,
		lineHeight: 21,
		letterSpacing: -0.32,
	},
	subheadline: {
		fontFamily: 'OpenSans',
		fontStyle: 'normal',
		fontWeight: 'normal',
		fontSize: 15,
		lineHeight: 20,
		letterSpacing: -0.24,
	},
	footnote: {
		fontFamily: 'OpenSans',
		fontStyle: 'normal',
		fontWeight: 'normal',
		fontSize: 13,
		lineHeight: 18,
		letterSpacing: -0.078,
	},
	caption1: {
		fontFamily: 'OpenSans',
		fontStyle: 'normal',
		fontWeight: 'normal',
		fontSize: 12,
		lineHeight: 16,
	},
	caption2: {
		fontFamily: 'OpenSans',
		fontStyle: 'normal',
		fontWeight: 'normal',
		fontSize: 11,
		lineHeight: 13,
		letterSpacing: 0.066,
	},
};
